sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

dist: trusty

cache: cargo

script:
  - cargo build --all
  # - cargo test --verbose --all

matrix:
  allow_failures:
    - rust: nightly
